apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
    type: front-end
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 8080
        name: http-webapp-svc
